### ISSUE TITLE
Баг із відображенням тіла публікації в safary на iOS

### ISSUE THREAD

**Issue by KostyaTretyak** [mblog-dev/wish#2]
@p-butovets повідомив, що бачить ось таку картину на усіх мобільних браузерах (Chrome 102, Safari та Bluefy) на iOS 15.4:

<details>
  <summary>Велика картинка</summary>
  
![photo1655970795](https://user-images.githubusercontent.com/2286306/175865584-86b80e4c-6893-4a9d-9e43-d08d972ff73c.jpg)
  
</details>

**Comment by KostyaTretyak** [comment]
@p-butovets, якщо у вас є блокувальники реклами, можливо це їхня робота. Спробуйте вимкнути їх, сподіваюсь це допоможе.

**Comment by p-butovets** [comment]
нема блокувальників. помилка виникає на трьох iOS пристріях, що доступні. Браузери Chrome, Safari, Bluefy

**Comment by KostyaTretyak** [comment]
Виявляється, що така ж проблема є і на десктопах: https://prnt.sc/8FQGTLJDUIjY

**Comment by KostyaTretyak** [comment]
Створив [issue на Angular](https://github.com/angular/angular/issues/46656)

**Comment by KostyaTretyak** [comment]
@p-butovets, перевірте будь-ласка, схоже проблему вирішено.

**Comment by p-butovets** [comment]
@KostyaTretyak так, все добре:)
